---
- name: Ensure sysstat is installed
  ansible.builtin.apt:
    name:
      - sysstat
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Ensure sysstat-collect.timer is configured
  ansible.builtin.template:
    src: templates/sysstat-collect.timer.j2
    dest: /etc/systemd/system/sysstat-collect.timer
    owner: root
    group: root
    mode: "644"
  notify: Restart sysstat-collect.timer

- name: Ensure sysstat-summary.timer is enabled
  ansible.builtin.systemd:
    name: sysstat-summary.timer
    enabled: true
    daemon_reload: true
